version: "3.8"

services:
  fizzbuzz-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fizzbuzz-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    networks:
      - fizzbuzz-network

networks:
  fizzbuzz-network:
    driver: bridge
