global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'fizzbuzz-server'
    scrape_interval: 10s
    static_configs:
      - targets: ['fizzbuzz-server:8080']
    metrics_path: /metrics